export const FETCH_FILES_BEGIN = 'FETCH_FILES_BEGIN'
export const FETCH_FILES_SUCCESS = 'FETCH_FILES_SUCCESS'
export const FETCH_FILES_FAIL = 'FETCH_FILES_FAIL'

export const DELETE_FILE_BEGIN = 'DELETE_FILE_BEGIN'
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS'
export const DELETE_FILE_FAIL = 'DELETE_FILE_FAIL'

export const UPLOAD_FILE_BEGIN = 'UPLOAD_FILE_BEGIN'
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS'
export const UPLOAD_FILE_FAIL = 'UPLOAD_FILE_FAIL'

export const UPDATE_FILE_BEGIN = 'UPDATE_FILE_BEGIN'
export const UPDATE_FILE_SUCCESS = 'UPDATE_FILE_SUCCESS'
export const UPDATE_FILE_FAIL = 'UPDATE_FILE_FAIL'

export const FETCH_SINGLE_FILE_BEGIN = 'FETCH_SINGLE_FILE_BEGIN'
export const FETCH_SINGLE_FILE_SUCCESS = 'FETCH_SINGLE_FILE_SUCCESS'
export const FETCH_SINGLE_FILE_FAIL = 'FETCH_SINGLE_FILE_FAIL'

export const READ_CACHE = 'READ_CACHE'

export const LOGIN_BEGIN = 'LOGIN_BEGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const LOGOUT = 'LOGOUT'

export const REGISTER_BEGIN = 'REGISTER_BEGIN'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const FETCH_USER_INFO_BEGIN = 'FETCH_USER_INFO_BEGIN'
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS'
export const FETCH_USER_INFO_FAIL = 'FETCH_USER_INFO_FAIL'

export const UPDATE_USER_PREFERENCES_BEGIN = 'UPDATE_USER_PREFERENCES_BEGIN'
export const UPDATE_USER_PREFERENCES_SUCCESS = 'UPDATE_USER_PREFERENCES_SUCCESS'
export const UPDATE_USER_PREFERENCES_FAIL = 'UPDATE_USER_PREFERENCES_FAIL'